# TODO reword timestamp columns
TIMESTAMP_COLUMN = "timestamp(ms)"
TIMESTAMP_ORIGINAL_COLUMN = "timestampFloat(ms)"
EYE_TRACKING_DISTANCE_BETWEEN_POINTS = "distanceGazeToZeroPoint"

EYE_TRACKING_COLUMN_DISTANCE_SENSOR_REFERENCE = "distanceSensorReference"
EYE_TRACKING_COLUMN_RGB_SENSOR_REFERENCE = "rgbSensorReference"
EYE_TRACKING_COLUMN_LIGHT_REFERENCE = "lightSensorReference"

EYE_TRACKING_REFERENCE_COLUMNS = [
    EYE_TRACKING_COLUMN_DISTANCE_SENSOR_REFERENCE,
    EYE_TRACKING_COLUMN_RGB_SENSOR_REFERENCE,
    EYE_TRACKING_COLUMN_LIGHT_REFERENCE,
]

EYE_TRACKING_COLUMN_PUPIL_RIGHT = "PupilRight"
EYE_TRACKING_COLUMN_PUPIL_LEFT = "PupilLeft"
EYE_TRACKING_COLUMN_ZERO_POINT_X = "ZeroPoint1"
EYE_TRACKING_COLUMN_ZERO_POINT_Y = "ZeroPoint2"
EYE_TRACKING_COLUMN_ZERO_POINT_Z = "ZeroPoint3"
EYE_TRACKING_COLUMN_GAZE_POINT_X = "GazePoint1"
EYE_TRACKING_COLUMN_GAZE_POINT_Y = "GazePoint2"
EYE_TRACKING_COLUMN_GAZE_POINT_Z = "GazePoint3"
EYE_TRACKING_COLUMN_VERGENCE_ANGLE = "VergenceAngle"
EYE_TRACKING_COLUMN_VERGENCE_ERROR = "VergenceError"
EYE_TRACKING_COLUMN_FRAME_INDEX = "index"

EYE_TRACKING_COLUMNS_DATA = [
    TIMESTAMP_COLUMN,
    "VideoTime",
    # XXX does this column exists everywhere?
    "VideoFileIndex",
    "Category",
    EYE_TRACKING_COLUMN_PUPIL_RIGHT,
    EYE_TRACKING_COLUMN_PUPIL_LEFT,
    "EyeballRightX",
    "EyeballRightY",
    "EyeballRightZ",
    "EyeballLeftX",
    "EyeballLeftY",
    "EyeballLeftZ",
    "RgazeVectorX",
    "RgazeVectorY",
    "RgazeVectorZ",
    "LeftGazeVectorX",
    "LeftGazeVectorY",
    "LeftGazeVectorZ",
    EYE_TRACKING_COLUMN_ZERO_POINT_X,
    EYE_TRACKING_COLUMN_ZERO_POINT_Y,
    EYE_TRACKING_COLUMN_ZERO_POINT_Z,
    EYE_TRACKING_COLUMN_GAZE_POINT_X,
    EYE_TRACKING_COLUMN_GAZE_POINT_Y,
    EYE_TRACKING_COLUMN_GAZE_POINT_Z,
    EYE_TRACKING_COLUMN_VERGENCE_ANGLE,
    EYE_TRACKING_COLUMN_VERGENCE_ERROR,
    EYE_TRACKING_COLUMN_FRAME_INDEX,
]
EYE_TRACKING_COLUMNS_DATA_WITH_REFERENCES = (
    EYE_TRACKING_COLUMNS_DATA
    + EYE_TRACKING_REFERENCE_COLUMNS
    + [EYE_TRACKING_DISTANCE_BETWEEN_POINTS]
)

# TODO rename variable names
HEADER_SENSOR_DATA0_RGB = [
    TIMESTAMP_COLUMN,
    "infrared",
    "red",
    "green",
    "blue light intensities",
]

LIGHT_SENSOR_COLUMN_ULTRAVIOLET = "ultraviolet"
LIGHT_SENSOR_COLUMN_INFRARED = "infrared"
LIGHT_SENSOR_COLUMN_WHITE_LIGHT_INTENSITY = "white light intensities"

HEADER_SENSOR_DATA1_LIGHT = [
    TIMESTAMP_COLUMN,
    LIGHT_SENSOR_COLUMN_ULTRAVIOLET,
    LIGHT_SENSOR_COLUMN_INFRARED,
    LIGHT_SENSOR_COLUMN_WHITE_LIGHT_INTENSITY,
]
SENSOR_COLUMN_DISTANCE = "distance(mm)"
DISTANCE_SENSOR_COLUMN_INDEX = "index"

HEADER_SENSOR_DATA2_DISTANCE = [TIMESTAMP_COLUMN, SENSOR_COLUMN_DISTANCE]
SENSOR_DATA_COLUMNS = ["data1", "data2", "data3", "data4"]

SENSOR_NUMBER_COLUMN = "sensorNumber"
SENSOR_COLUMN_NAMES = [TIMESTAMP_COLUMN] + SENSOR_DATA_COLUMNS

HEADER_SENSOR_IMPORT_NAMES = [
    TIMESTAMP_COLUMN,
    # XXX check column names exists or are in every file
    "frameIndex",
    "sensorIndex",
    SENSOR_NUMBER_COLUMN,
] + SENSOR_DATA_COLUMNS

DISTANCE_SENSOR_COLUMNS_ALL = [
    DISTANCE_SENSOR_COLUMN_INDEX,
    TIMESTAMP_ORIGINAL_COLUMN,
    SENSOR_COLUMN_DISTANCE,
    TIMESTAMP_COLUMN,
]

DISTANCE_SENSOR_INVERSE_COLUMN = "inverseDistance([1/m])"
ACF_COLUMN_INTERCEPT_SLOPE = "x-axis intercept lag_1 T[s]"

HEADER_REFRACTION_ERROR_INDEX = "index"
HEADER_REFRACTION_ERROR_RIGHT_EYE = "R"
HEADER_REFRACTION_ERROR_LEFT_EYE = "L"